_car = _this;
_grp2 = createGroup East;
_driver = _grp2 createUnit ["O_Soldier_Lite_F",[0,0,0],[],0,"NONE"];
_driver assignAsDriver _car;
_driver moveInDriver _car;
[_driver] call fnc_SetUnit;
_driver action ["EngineOn", _car];
_car call fnc_MakeProtected;
_car allowCrewInImmobile True;
_car setDir random 360;
_car forceSpeed 0;
_car lock 2;